### PR TITLE
fix panics on service filter

### LINKED ISSUE #561: segmentation violation code=0x1 addr=0x0 pc=0x6d8ea5d]
```console
$ cloudlist -s s3

  _______             _____     __ 
 / ___/ /__  __ _____/ / (_)__ / /_
/ /__/ / _ \/ // / _  / / (_-</ __/
\___/_/\___/\_,_/\_,_/_/_/___/\__/ 

		projectdiscovery.io

[INF] Current cloudlist version 1.0.9 (latest)
[INF] Listing assets from provider: gcp services: s3 id: staging
alpha-storage-bucket.storage.googleapis.com
beta-backups-bucket.storage.googleapis.com
gamma-static-assets.storage.googleapis.com
delta-source-uploads.storage.googleapis.com
epsilon-cloud-data.storage.googleapis.com
zeta-terraform-state.storage.googleapis.com
eta-build-artifacts.storage.googleapis.com
theta-dev-logs.storage.googleapis.com
iota-exports-bucket.storage.googleapis.com
kappa-screenshots-bucket.storage.googleapis.com
lambda-results-bucket.storage.googleapis.com
mu-template-storage.storage.googleapis.com
nu-test-bucket.storage.googleapis.com
xi-poc-bucket.storage.googleapis.com
omicron-cloud-build.storage.googleapis.com
pi-optimized-images.storage.googleapis.com
rho-cloud-backups.storage.googleapis.com
sigma-dev-bucket.storage.googleapis.com
[INF] Found 18 Hosts for gcp (staging)
[INF] Listing assets from provider: cloudflare services:  id: 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6d8ea5d]

goroutine 1 [running]:
github.com/projectdiscovery/cloudlist/internal/runner.(*Runner).Enumerate(0xc001826140)
	github.com/projectdiscovery/cloudlist/internal/runner/runner.go:93 +0x8dd
main.main()
	./main.go:14 +0x89
```

### PR DESCRIPTION
**Pull request by RamanaReddy0M**
- closes #561

### CODE REVIEW

File: pkg/providers/consul/consul.go [hunk 1]
```diff
@@ -121,6 +121,10 @@ const (
 
 // Resources returns the provider for an resource deployment source.
 func (p *Provider) Resources(ctx context.Context) (*schema.Resources, error) {
+	finalList := schema.NewResources()
```
Comment (dogancanbakir) [inline pkg/providers/consul/consul.go:124]: finalResources?

**Review by dogancanbakir — APPROVED** [review]

**Review by dogancanbakir — APPROVED** [review]

**Review by ehsandeep — APPROVED** [review]
